### ISSUE TITLE
add ko-KR README

### ISSUE THREAD

**Issue by danbom** [gmatthewsfeuer/next-plate#118]
## Expected Behavior
Add the `README.ko-KR.md` file and update default [README](https://github.com/gmatthewsfeuer/next-plate/blob/main/README.md).

## Current Behavior
The Korean version of README will be added.
![image](https://user-images.githubusercontent.com/52441697/178190340-dc9e0f4b-f9fe-442c-8bc2-38d61c64e6d7.png)
![image](https://user-images.githubusercontent.com/52441697/178190372-782b7361-edda-4608-a950-fabc79867bb2.png)

## Possible Solution
I uploaded 'README.ko-KR.md' in a forked repository, so I would appreciate it if you could allow me to open a pull request.

## Context
It's a good project, and I had the best template experience by looking at the project and using it myself. I hope other Koreans besides me can access this good project more easily!

Thank you.

**Comment by gmatthewsfeuer** [comment]
@danbom I'm so glad you liked the project and you want to collaborate with the project!
I will allow you to open a pull request 🤗

Thank you very much!
